source 'https://rubygems.org'

gem "github-pages", group: :jekyll_plugins

git "https://github.com/jekyll/minima", branch: "2.5-stable" do
  gem "minima"
end

group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-youtube"
end

gem "csv"
gem "webrick", "~> 1.8"

gem "html-proofer", "~> 5.0"
